#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PayMayaSDK_Example', :exclusive => true do
  pod "PayMayaSDK", :path => "../"
end

target 'PayMayaSDK_Tests', :exclusive => true do
  pod "PayMayaSDK", :path => "../"

  
end
