#source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '7.0'

target 'PayMayaSDK_Example' do
  pod 'PayMayaSDK', :path => '../'
	pod 'CardIO'
end

target 'PayMayaSDK_Tests' do
  pod 'PayMayaSDK', :path => '../'
end
